# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-scribble

# >> macros
# << macros

Summary:    Scribble
Version:    0.5
Release:    2
Group:      Qt/Qt
License:    GPLv3
URL:        https://github.com/poetaster/harbour-scribble
Source0:    %{name}-%{version}.tar.bz2
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils
BuildRequires:  qt5-qttools-linguist

%description
Simple drawing application.

%if "%{?vendor}" == "chum"
PackageName: Scribble
Type: desktop-application
Categories:
 - Graphics
DeveloperName: Mark Washeim (poetaster)
Custom:
 - Repo: https://github.com/poetaster/harbour-scribble
Icon: https://raw.githubusercontent.com/poetaster/harbour-scribble/master/icons/172x172/harbour-scribble.png
Screenshots:
 - https://raw.githubusercontent.com/poetaster/harbour-scribble/main/screenshot-01_0.png
 - https://raw.githubusercontent.com/poetaster/harbour-scribble/main/screenshot-02_0.png
 - https://raw.githubusercontent.com/poetaster/harbour-scribble/main/screenshot-03_0.png
Url:
  Homepage: https://github.com/poetaster/harbour-scribble
  Help: https://github.com/poetaster/harbour-scribble/discussions
  Bugtracker: https://github.com/poetaster/harbour-scribble/issues
  Donation: https://www.paypal.me/poetasterFOSS
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake5 

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
